// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: pangram/v1/game.proto

package gamepb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WordResult int32

const (
	WordResult_ERROR          WordResult = 0
	WordResult_OK             WordResult = 1
	WordResult_TOO_SHORT      WordResult = 2
	WordResult_INVALID_LETTER WordResult = 3
	WordResult_MISSING_CENTER WordResult = 4
	WordResult_NOT_IN_DICT    WordResult = 5
	WordResult_DUPLICATE      WordResult = 6
)

// Enum value maps for WordResult.
var (
	WordResult_name = map[int32]string{
		0: "ERROR",
		1: "OK",
		2: "TOO_SHORT",
		3: "INVALID_LETTER",
		4: "MISSING_CENTER",
		5: "NOT_IN_DICT",
		6: "DUPLICATE",
	}
	WordResult_value = map[string]int32{
		"ERROR":          0,
		"OK":             1,
		"TOO_SHORT":      2,
		"INVALID_LETTER": 3,
		"MISSING_CENTER": 4,
		"NOT_IN_DICT":    5,
		"DUPLICATE":      6,
	}
)

func (x WordResult) Enum() *WordResult {
	p := new(WordResult)
	*p = x
	return p
}

func (x WordResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WordResult) Descriptor() protoreflect.EnumDescriptor {
	return file_pangram_v1_game_proto_enumTypes[0].Descriptor()
}

func (WordResult) Type() protoreflect.EnumType {
	return &file_pangram_v1_game_proto_enumTypes[0]
}

func (x WordResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WordResult.Descriptor instead.
func (WordResult) EnumDescriptor() ([]byte, []int) {
	return file_pangram_v1_game_proto_rawDescGZIP(), []int{0}
}

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_pangram_v1_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pangram_v1_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_pangram_v1_game_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type CreateGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Letters       []string               `protobuf:"bytes,3,rep,name=letters,proto3" json:"letters,omitempty"`
	Center        string                 `protobuf:"bytes,4,opt,name=center,proto3" json:"center,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	mi := &file_pangram_v1_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pangram_v1_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_pangram_v1_game_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGameResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateGameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGameResponse) GetLetters() []string {
	if x != nil {
		return x.Letters
	}
	return nil
}

func (x *CreateGameResponse) GetCenter() string {
	if x != nil {
		return x.Center
	}
	return ""
}

type SubmitWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Word          string                 `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWordRequest) Reset() {
	*x = SubmitWordRequest{}
	mi := &file_pangram_v1_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWordRequest) ProtoMessage() {}

func (x *SubmitWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pangram_v1_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWordRequest.ProtoReflect.Descriptor instead.
func (*SubmitWordRequest) Descriptor() ([]byte, []int) {
	return file_pangram_v1_game_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitWordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubmitWordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type SubmitWordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Reason        WordResult             `protobuf:"varint,2,opt,name=reason,proto3,enum=pangram.v1.WordResult" json:"reason,omitempty"`
	Points        int32                  `protobuf:"varint,3,opt,name=points,proto3" json:"points,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Pangram       bool                   `protobuf:"varint,5,opt,name=pangram,proto3" json:"pangram,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWordResponse) Reset() {
	*x = SubmitWordResponse{}
	mi := &file_pangram_v1_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWordResponse) ProtoMessage() {}

func (x *SubmitWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pangram_v1_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWordResponse.ProtoReflect.Descriptor instead.
func (*SubmitWordResponse) Descriptor() ([]byte, []int) {
	return file_pangram_v1_game_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitWordResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *SubmitWordResponse) GetReason() WordResult {
	if x != nil {
		return x.Reason
	}
	return WordResult_ERROR
}

func (x *SubmitWordResponse) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *SubmitWordResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SubmitWordResponse) GetPangram() bool {
	if x != nil {
		return x.Pangram
	}
	return false
}

var File_pangram_v1_game_proto protoreflect.FileDescriptor

const file_pangram_v1_game_proto_rawDesc = "" +
	"\n" +
	"\x15pangram/v1/game.proto\x12\n" +
	"pangram.v1\"'\n" +
	"\x11CreateGameRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\"j\n" +
	"\x12CreateGameResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aletters\x18\x03 \x03(\tR\aletters\x12\x16\n" +
	"\x06center\x18\x04 \x01(\tR\x06center\"7\n" +
	"\x11SubmitWordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04word\x18\x02 \x01(\tR\x04word\"\xa2\x01\n" +
	"\x12SubmitWordResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12.\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x16.pangram.v1.WordResultR\x06reason\x12\x16\n" +
	"\x06points\x18\x03 \x01(\x05R\x06points\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x18\n" +
	"\apangram\x18\x05 \x01(\bR\apangram*v\n" +
	"\n" +
	"WordResult\x12\t\n" +
	"\x05ERROR\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\r\n" +
	"\tTOO_SHORT\x10\x02\x12\x12\n" +
	"\x0eINVALID_LETTER\x10\x03\x12\x12\n" +
	"\x0eMISSING_CENTER\x10\x04\x12\x0f\n" +
	"\vNOT_IN_DICT\x10\x05\x12\r\n" +
	"\tDUPLICATE\x10\x062\xa7\x01\n" +
	"\vGameManager\x12K\n" +
	"\n" +
	"CreateGame\x12\x1d.pangram.v1.CreateGameRequest\x1a\x1e.pangram.v1.CreateGameResponse\x12K\n" +
	"\n" +
	"SubmitWord\x12\x1d.pangram.v1.SubmitWordRequest\x1a\x1e.pangram.v1.SubmitWordResponseB8Z6github.com/luispellizzon/pangram/api/pangram/v1;gamepbb\x06proto3"

var (
	file_pangram_v1_game_proto_rawDescOnce sync.Once
	file_pangram_v1_game_proto_rawDescData []byte
)

func file_pangram_v1_game_proto_rawDescGZIP() []byte {
	file_pangram_v1_game_proto_rawDescOnce.Do(func() {
		file_pangram_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pangram_v1_game_proto_rawDesc), len(file_pangram_v1_game_proto_rawDesc)))
	})
	return file_pangram_v1_game_proto_rawDescData
}

var file_pangram_v1_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pangram_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pangram_v1_game_proto_goTypes = []any{
	(WordResult)(0),            // 0: pangram.v1.WordResult
	(*CreateGameRequest)(nil),  // 1: pangram.v1.CreateGameRequest
	(*CreateGameResponse)(nil), // 2: pangram.v1.CreateGameResponse
	(*SubmitWordRequest)(nil),  // 3: pangram.v1.SubmitWordRequest
	(*SubmitWordResponse)(nil), // 4: pangram.v1.SubmitWordResponse
}
var file_pangram_v1_game_proto_depIdxs = []int32{
	0, // 0: pangram.v1.SubmitWordResponse.reason:type_name -> pangram.v1.WordResult
	1, // 1: pangram.v1.GameManager.CreateGame:input_type -> pangram.v1.CreateGameRequest
	3, // 2: pangram.v1.GameManager.SubmitWord:input_type -> pangram.v1.SubmitWordRequest
	2, // 3: pangram.v1.GameManager.CreateGame:output_type -> pangram.v1.CreateGameResponse
	4, // 4: pangram.v1.GameManager.SubmitWord:output_type -> pangram.v1.SubmitWordResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pangram_v1_game_proto_init() }
func file_pangram_v1_game_proto_init() {
	if File_pangram_v1_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pangram_v1_game_proto_rawDesc), len(file_pangram_v1_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pangram_v1_game_proto_goTypes,
		DependencyIndexes: file_pangram_v1_game_proto_depIdxs,
		EnumInfos:         file_pangram_v1_game_proto_enumTypes,
		MessageInfos:      file_pangram_v1_game_proto_msgTypes,
	}.Build()
	File_pangram_v1_game_proto = out.File
	file_pangram_v1_game_proto_goTypes = nil
	file_pangram_v1_game_proto_depIdxs = nil
}
